/**
 * Created by zhangf on 2016-12-29.
 */

/*
* 
* 首页
* */
export const INDEX_GET_LIST_SUCCESS = 'INDEX_GET_LIST_SUCCESS';
export const INDEX_GET_DONELIST_SUCCESS = 'INDEX_GET_DONELIST_SUCCESS';
export const INDEX_SET_DONELISTTYPE_SUCCESS = 'INDEX_SET_DONELISTTYPE_SUCCESS';
export const INDEX_RESET_LISTDATA_SUCCESS = 'INDEX_RESET_LISTDATA_SUCCESS';
export const INDEX_RESET_DONELISTDATA_SUCCESS = 'INDEX_RESET_DONELISTDATA_SUCCESS';
export const INDEX_RESET_CONTINUETOLOAD_SUCCESS = 'INDEX_RESET_CONTINUETOLOAD_SUCCESS';

// export const INDEX_GET_IMG_SUCCESS = 'INDEX_GET_IMG_SUCCESS';

/**
* 初始化
*/
export const INIT_SERVER_AND_USER = 'INIT_SERVER_AND_USER';
export const INIT_SETTING_SOURCE = 'INIT_SETTING_SOURCE';


/*详情页*/
export const DETAIL_GETTODO_SUCCESS = 'DETAIL_GETTODO_SUCCESS';
export const DETAIL_GETTODOCONTENT_SUCCESS = 'DETAIL_GETTODOCONTENT_SUCCESS';
export const DETAIL_GETTODOOPINION_SUCCESS = 'DETAIL_GETTODOOPINION_SUCCESS';
export const DETAIL_GETTODOATTACHS_SUCCESS = 'DETAIL_GETTODOATTACHS_SUCCESS';
export const DETAIL_GETOPETATIONS_SUCCESS = 'DETAIL_GETOPETATIONS_SUCCESS';
export const DETAIL_SETISSHOWREPLYPAGE_SUCCESS = 'DETAIL_SETISSHOWREPLYPAGE_SUCCESS';
export const DETAIL_REPLYOPINION_SUCCESS = 'DETAIL_REPLYOPINION_SUCCESS';